### ISSUE TITLE
I cannot run migrations

### ISSUE THREAD

**Issue by ackahblayy** [idlesign/django-siteflags#2]
When I add ModelWithFlag to my model I can run migrations. Eg.
`class Property(models.Model, ModelWithFlag):`
I get an error `TypeError: Cannot create a consistent method resolution
order (MRO) for bases Model, ModelWithFlag`

traceback:
`python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Program Files\Python36\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Program Files\Python36\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "C:\Program Files\Python36\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Program Files\Python36\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Program Files\Python36\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\bern8\Desktop\Aurora\final lavue project\vue\app\models.py", line 65, in <module>
    class Amenity(models.Model, ModelWithFlag):
  File "C:\Program Files\Python36\lib\site-packages\django\db\models\base.py", line 88, in __new__
    new_class = super_new(cls, name, bases, new_attrs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Model, ModelWithFlag`

**Comment by idlesign** [comment]
Thank you for the report.

I guess that's a typo in docs: no need to inherit from both `models.Model` and `ModelWithFlag`, since the later is already a descendant of `models.Model`. 

It should be fixed now, give it a try.
